service: todo-list

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  getTodo:
    handler: todos/read.getTodo
    events:
      - http:
          path: todo
          method: get
  createTodo:
    handler: todos/create.createTodo
    events:
      - http:
          path: todo
          method: post
