service: todo-list

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

package:
  include:
    - todos/**
    - models/**

functions:
  listTodos:
    handler: todos/read.listTodos
    events:
      - http:
          path: todos
          method: get
  getTodo:
    handler: todos/read.getTodo
    events:
      - http:
          path: todo/{id}
          method: get
  createTodo:
    handler: todos/create.createTodo
    events:
      - http:
          path: todo
          method: post
  updateTodo:
    handler: todos/update.updateTodo
    events:
      - http:
          path: todo/{id}
          method: patch
  deleteTodo:
    handler: todos/delete.deleteTodo
    events:
      - http:
          path: todo/{id}
          method: delete
